language: node_js
node_js: '6'
os: linux
dist: trusty
osx_image: xcode8.3
sudo: false
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
addons:
  apt:
    packages:
    - fakeroot
    - rpm
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+/"
install:
- yarn install
script:
- if test -z "$TRAVIS_TAG"; then yarn run make; fi
deploy:
  provider: script
  skip_cleanup: true
  script: ci/travis-deploy.sh
  on:
    tags: true
env:
  global:
  - secure: ubvGof7sZN+uVVUhKYmmV7d+zZ0A+utNX/tG7TA5vBh7G/p9bGufdgvBnt0zb76gXN3MrPIbzkfrFEmkJQpSrcLdYDYa9K/LE+miV8l8kMEzovetmH+6pxDH1qd5dPI+kOm43e1izHMxPOfALTp/rpvGq/Anl641XAQRWfsgt7YQAikcBo3wXUx63Bwa1PcZodbpa1l2eJ+tG1V4Q40Bol2UnGnr3/HV7l6sK3sooNIXLh2sb6Ul7dWMiZgozXnV+mgC1PteY8ZElgVIEXvVsSARyrieBs7IkkOJRNkusHJLKGkrT0xO1EoQVs2Ue0Y+TRlBhwlmOLIv9OM+mTGYfXf9CVNm3nCFAGb7toH4JsYiVl+1SAhFOHblcJurVmWl0cEHDtCFYK2YbtFYjvrr9ynplCNnQJ4FserTiy+ywjYfnLzqQ4Zc/CRB5EbX1lDuHZPlgSUh7sfVQvTb+zQFwkLsf8RW7UacZRMvBB1UAvJzZYYfCbuztNRZT8Zyve1jmKY2yH0CUz/SlcS4n65CJlwXq6piaCwCiQZC2xJHcDWmmK+FJgcFo5XPRWLge6EW3BuAcas3M+s6/BL69nLnbslqcmoRMGUEFjnIXVt42Z+jYuUfNbFllYUz1femvRHp5FP0pSQ+2h7UFGbX5yM0+1XRE5afmOJw9hzvdIXk8Ss=
